### ISSUE TITLE
翻译有误

### ISSUE THREAD

**Issue by thjxs** [LCTT/TranslateProject#10645]
文章：https://linux.cn/article-9687-1.html
文末的 “在世” 是笔误？
>那么，就是这样。到此为止，您应该对 cron 任务以及如何`在世`使用它们有了一个基本的了解。后续还会介绍更多的优秀工具。敬请关注！！

**Comment by wxy** [comment]
谢谢，是错误了。应该是“您应该对 cron 任务以及如何实时使用它们有了一个基本的了解”
