### ISSUE TITLE
完善 CI

### ISSUE THREAD

**Issue by vizv** [LCTT/TranslateProject#11095]
跟踪 CI 完善程度

- [X] 变更的基本分析和检查
- [X] 文章类别检查
- [X] 变更列表一致性检查
- [ ] **高优先**：跳过 merge commit
- [ ] Markdown 语法检查
- [ ] 文件名规则检查
- [ ] 推送前本地检查
- [ ] 匹配规则单元测试
- [ ] Travis CI 的 `ShellCheck` 依赖项目以及启用 `check/check.sh` 进行 shell 语法风格检查
- [ ] 新规则：发布后的文章仍可能被校对
- [ ] 文章末尾贡献者检查

@wxy 留言中补充

**Comment by oska874** [comment]
能否自动检查文章末尾的 `译者、校对、选题、作者` 这几项的内容是否有缺失？比如译者忘记了写自己的id，或者写错了id

**Comment by oska874** [comment]
可以检查markdown 语法是否有错？

**Comment by vizv** [comment]
> 可以检查markdown 语法是否有错？

有什么工具么？

**Comment by bestony** [comment]
markdown 语法检查试试： https://github.com/markdownlint/markdownlint ？

**Comment by wxy** [comment]
@vizv 是不是可以迁移到 github 的 CI 上，Travis CI 感觉挺慢。

**Comment by vizv** [comment]
好，安排上了
