### ISSUE TITLE
“Free” 何时被翻译为“自由”，何时被翻译为“免费”

### ISSUE THREAD

**Issue by wxy** [LCTT/TranslateProject#11253]
_Originally posted by @HankChow in https://github.com/LCTT/TranslateProject/pull/11236#issuecomment-439585338_

**Comment by wxy** [comment]
是这样，确实在很多场景中，“自由”和“免费”难以区分，甚至含义兼备的。我判断这个的考虑是：

如和“Open/Opensource” 一起提及，那应该是指 FOSS——Free and Open Source Software，所以这种情况下，我都译作“自由”。
如果该软件的许可证采用自由软件许可证，为了强调该许可证的含义，我也译作“自由”。
只有该软件是源代码不公开的，或者采用专有许可证的，但是又允许“免费”使用的，我才视作“免费”。
这个 issue 提的非常好，我也会请大家一起来讨论。

**Comment by fuzheng1998** [comment]
得看语境吧，要是讲钱的问题就是免费；要是比较严肃的事情，有深刻的意义就是自由吧

**Comment by Vic020** [comment]
zh一般看是否大写，如果是跟常用词搭配在一起，

> 是这样，确实在很多场景中，“自由”和“免费”难以区分，甚至含义兼备的。我判断这个的考虑是：
> 
> * 如和“Open/Opensource” 一起提及，那应该是指 FOSS——Free and Open Source Software，所以这种情况下，我都译作“自由”。
> * 如果该软件的许可证采用自由软件许可证，为了强调该许可证的含义，我也译作“自由”。
> * 只有该软件是源代码不公开的，或者采用专有许可证的，但是又允许“免费”使用的，我才视作“免费”。
> 
> 这个 issue 提的非常好，我也会请大家一起来讨论。

非常赞同第一点，补充一个小技巧，为自由时候，在软件领域大多为大写

**Comment by MZqk** [comment]
”Think of free as in free speech, not as in free beer“在维基上看到的解释——言论是自由的，而啤酒可以是免费的。

**Comment by yjacks** [comment]
就我自己翻译来说，使用「for free」等特殊句式统一翻译为「免费」
is free等翻译为「自由」
Free software通常指「自由软件」，视语义可能翻译为「免费软件」（这种情况都够加上译注了，，，）
