### ISSUE TITLE
《Lisp 是怎么成为上帝的编程语言的》翻译有误

### ISSUE THREAD

**Issue by no1xsyzy** [LCTT/TranslateProject#11320]
相关页面：
[于 linux.cn](https://linux.cn/article-10255-1.html)
[于 GitHub](https://github.com/LCTT/TranslateProject/blob/9ed71b7cea071a7d16854d79942b7830abc31d8e/published/20181014%20How%20Lisp%20Became%20God-s%20Own%20Programming%20Language.md)

Lambda 微积分 -> Lambda 演算
Python 有了列表理解 -> Python 有了列表推导式

**Comment by no1xsyzy** [comment]
另外，不清楚这种是否有需要译注。

> 名字是四个字母的语言。

参见 [四字神名 - 维基百科，自由的百科全书](https://zh.wikipedia.org/wiki/%E5%9B%9B%E5%AD%97%E7%A5%9E%E5%90%8D)

**Comment by wxy** [comment]
@Northurland

**Comment by Northurland** [comment]
@no1xsyzy 
非常对不起……我想您应该是正确的。
我得承认，我并不知道文章中许多技术性名词的中文译名，而在查资料时也没有找到正式的中文翻译。这种擅自翻译、依赖校对的做法和心态，回想起来的确不负责任。我会在以后的翻译中尽量避免这种情况发生。
或许我需要一本专业词典来解决这个问题。

至于您提到的这个宗教典故……我认为可以加一个译注，尽管单看歌词我并不是很确定原文是否真的在引用这个典故，但引用的可能性显然很大。

@wxy 组长，请问需要如何处理？

**Comment by wxy** [comment]
@no1xsyzy 谢谢您的指正。
@Northurland 我会更新修正。也不用太自责，你已经做的很好了。

**Comment by wxy** [comment]
#11340

**Comment by Northurland** [comment]
@wxy 
收到。话说回来，有什么比较好用的专业术语翻译对照表吗？组长给推荐一个？
