### ISSUE TITLE
是否有兴趣和我一起校对 svnbook-1.8

### ISSUE THREAD

**Issue by wuzhouhui** [LCTT/TranslateProject#12534]
看到  Linux 中国的志愿者非常活跃, 所以我希望能找一些志愿者和我一起翻译 svnbook-1.8, 我从 17 年 5 月开始翻译至今, 已经翻译完了 8 章, 正在翻译手册部分. 一个人翻译实在是太慢了, 希望能有更多的热心网友加入进来, 详情请见 http://svnbook.red-bean.com/index.zh.html

打扰

**Comment by wxy** [comment]
支持，大家可以看看~

**Comment by wuzhouhui** [comment]
最近, 中文版 svnbook-1.8 已经基本翻译完成, 但还需要人帮我校对. 我觉得不太好翻译的地方都在源码中用关键字 TODO 标记了出来, 希望能从 Linux 中国找到一些志愿者, 详情请看  http://svnbook.red-bean.com/index.zh.html
