### ISSUE TITLE
推荐选题

### ISSUE THREAD

**Issue by oska874** [LCTT/TranslateProject#16358]
自己动手使用 Rust 实现区块链-第一部分
https://blog.knoldus.com/custom-implementation-of-blockchain-in-rustpart-1/

**Comment by oska874** [comment]
Rust once and share it with Android, iOS and Flutter
https://dev.to/robertohuertasm/rust-once-and-share-it-with-android-ios-and-flutter-286o

**Comment by wxy** [comment]
@lujun9972
