### ISSUE TITLE
请教一个关于使用权的问题

### ISSUE THREAD

**Issue by mengxinayan** [LCTT/TranslateProject#17270]
请问我是否可以在我的文章中 使用/引用 我本人翻译的文章吗？如果可以，需要额外注明什么信息吗？
（文章主要放在博客上，**个人使用非商用**）

**Comment by wxy** [comment]
你完全可以转载或引用你或其他 LCTT 成员翻译的文章，我们的文章都是采用 CC 授权的，也就是说注明出处（比如来源、作译者）就可以的。

**Comment by mengxinayan** [comment]
谢谢解答，我明白了 : )
