### ISSUE TITLE
新文章建议

### ISSUE THREAD

**Issue by MjSeven** [LCTT/TranslateProject#21031]
关于这两篇文章
https://www.2daygeek.com/install-configure-ansible-automation-tool-linux-quick-start-guide/
https://www.2daygeek.com/ansible-ad-hoc-command-quick-start-guide-with-examples/
是当前仓库中下面这篇文章中的相关链接，劳烦可以补齐到仓库中
20200129 Ansible Playbooks Quick Start Guide with Examples.md

**Comment by lujun9972** [comment]
这两个已经被选题了，地址分别为
sources/tech/20200121 Ansible Automation Tool Installation, Configuration and Quick Start Guide.md
sources/tech/20200124 Ansible Ad-hoc Command Quick Start Guide with Examples.md
