### ISSUE TITLE
是否考虑翻译这个关于RMS的澄清letter？

### ISSUE THREAD

**Issue by JiaoXianjun** [LCTT/TranslateProject#21426]
您好，

我在rms-support的discord讨论频道里看到有人讨论wxy撤回了自己的signing，他们表示不理解。我觉得是不是wxy作为一个组织的leader最好保持中立？不代表就是反对rms-suppor？

此外，不知道你们是否考虑翻译这封关于RMS的澄清letter：https://jorgemorais.gitlab.io/justice-for-rms/

谢谢！

**Comment by wxy** [comment]
对于这件事，我们不表示反对，也不表示支持。
原本是表示支持的，但是作为一个**中国人**，我们认为 RMS 的发布在其博客的一些言论和偏见是不可接受的，所以我们不再对他表示支持。但是鉴于他对自由软件的贡献，我们也不反对他继续参与自由软件活动。因此，我们对此持中立态度。

**Comment by JiaoXianjun** [comment]
RMS关于中国的偏见，能否指明出处？我也想了解一下。谢谢！

**Comment by wxy** [comment]
> RMS关于中国的偏见，能否指明出处？我也想了解一下。谢谢！

请在其博客搜索“China”
