### ISSUE TITLE
How to request my website for linux.cn translation

### ISSUE THREAD

**Issue by arindam-giri** [LCTT/TranslateProject#22442]
Hi
I want to request the team to consider my website [www.debugpoint.com](https://www.debugpoint.com) for translation in linux.cn. What is the process of requesting the same?

Thanks
Arindam

**Comment by wxy** [comment]
@bestony @lujun9972 请评估这个事情~

**Comment by bestony** [comment]
@arindam-giri Hi, Arindam, i notice, you write these in your website - content-policy

```
Please do not copy/republish the whole articles, images from this site. I spend lots of time writing, designing articles.

You may link the URL of this site to your site. You may use a short paragraph (40 words) using a quote on your site. Provide original article URL link/credits before or after quoting this site.
```

If you want we translate your article, you must allow us to translate it into Chinese. you must writer a Authorization Letter to us .

please send email to `bestony@linux.com` ,and cc to `11440033@qq.com`

**Comment by wxy** [comment]
Or ,change your content police to CC-by.

**Comment by arindam-giri** [comment]
Hi
Thank you for your message and clarification. We have updated the content policy to Creative Commons Attribution-ShareAlike 4.0 International License.

It is available here. [https://www.debugpoint.com/content-policy/](https://www.debugpoint.com/content-policy/) 

I also emailed to the above email addresses. Please check and let me know what is the next step. Thanks.

**Comment by lujun9972** [comment]
It seems the promotion of the website
```
We bring the latest happenings in the Linux universe, app reviews, tutorials, easy to understand guides for you. Stay in touch via Telegram, Twitter, YouTube, and Facebook and never miss an update!
```
![](https://www.debugpoint.com/blog/wp-content/uploads/2020/07/telegramjoin1.png)
 and the content of posts are mixed, which means they are under the same tag(<div class='post-content description cf entry-content has-share-float content-spacious'>).

In this case, It is hard to separate the content from the promotion by script. 

That's will be greater if you could add an extra class to these promotion tags, Thank you.

**Comment by lujun9972** [comment]
There is nothing else need to do.
I have added debugpoint.com to the source of the post-picking script.

**Comment by wxy** [comment]
@arindam-giri Thanks you ~
