### ISSUE TITLE
有没有组织翻译https://lwn.net/Kernel/的意愿

### ISSUE THREAD

**Issue by jrglinux** [LCTT/TranslateProject#24117]
LWN的最新文章对于普通订阅者需要付费，老王有没有兴趣组织团队来实时更新这个网站内容呀

**Comment by wxy** [comment]
存在两个问题:

- LWN 付费文章既然设置了付费墙，那翻译而泄露过来就是不合理的
- LWN 文章比较生涩，能翻译好的人太少，说实话，受众也不多。

国内有个公众号（Linux news搬运工）在做这样的工作，感兴趣的同学可以支援他一下。
