### ISSUE TITLE
请求翻译ada语言帮助文件

### ISSUE THREAD

**Issue by cws999** [LCTT/TranslateProject#24115]
[帮助](http://www.ada-auth.org/standards/12rm/html/RM-TOC.html) [原理](http://www.ada-auth.org/standards/12rat/html/Rat12-TOC.html)

**Comment by wxy** [comment]
对于这样的工作，我不建议单方面的发起请求，而是鼓励身体力行的发起而招募愿意共襄盛举的朋友。
