### ISSUE TITLE
手动选题[Wow! Torvalds Modified Fedora Linux to Run on his Apple M2 Macbook]

### ISSUE THREAD

**Issue by zjsoftceo** [LCTT/TranslateProject#27152]
[Wow! Torvalds Modified Fedora Linux to Run on his Apple M2 Macbook]

**Comment by wxy** [comment]
如果你希望选题人员替你选题，你可以在这里 at 他。不过对于我们确定的选题源，一般不需要专门提醒，都会定时选题的。
