### ISSUE TITLE
是否考虑过使用经过审定的标准术语库？

### ISSUE THREAD

**Issue by w568w** [LCTT/TranslateProject#28598]
### Your Questions

[术语在线](https://www.termonline.cn/) 是由 [全国科学技术名词审定委员会](http://www.cnterm.cn/) 创建的术语仓库及搜索引擎，包含了经过全国科技名词委审定的专有学术名词。常见的、有一定历史的争议词语可以找到标准翻译，例如[词典](https://github.com/LCTT/TranslateProject/blob/master/Dict.md)中的：

1. **Repository**：（软件）储藏库 `《计算机科学技术名词》（第三版）`
2. **Shell**：命令解释程序 `《计算机科学技术名词》（第三版）`
3. **Fork**：（进程）复制 `《计算机科学技术名词》（第三版）`

---

此外可供参考的还有微软公司内部使用的基准术语库 [微软语言门户](https://www.microsoft.com/zh-cn/language/Search) 以及联合国大会和会议管理部审定的 [联合国术语数据库](https://untermportal.un.org/unterm2/zh/)，如：

1. **Fork**：创建分支

*p.s.* 联合国术语数据库罕见地提供了 [Live USB/CD](https://untermportal.un.org/unterm2/zh/view/e05d620b-2892-4d68-a59d-88cc7947e9fd) 的翻译（`日内瓦办事处`），可惜没有中文。不过其提供的其他语言翻译可供标准参考。

**Comment by wxy** [comment]
非常感谢您的建议和给出的资源。我需要慎重考虑。

我初步的想法是，如果有国家审定的名词，那就应该首先考虑国家的审定结果。
如果没有，或者不足以涵盖，那就考虑推荐新的译法。

比如说，上面提到的 Fork 一词，只指了进程方面的，采用“复制”一词或可考虑（虽然我觉得没办法和 copy 区分开）；但对于仓库、发行版的 Fork 行为，是否也采用此译法，我觉得需要斟酌。而采用“创建分支”的译法，或与 “Branch” 不好区分。

另外一个就是 Shell，这个确实是争议比较大，很多人已经习惯了 Shell 一词直接使用，是否翻译，采用哪种翻译，并不好觉得和取舍。

**Comment by w568w** [comment]
是的，我只是提出对于未来翻译的一个大致的建议，并非针对某一个或几个具体的词语翻译 😂 LCTT 有些现定的翻译未必不比列出的那些落后于时代的审定术语翻译得好。

如果能将这几个链接加入到翻译参考建议里、帮助到后来的其他翻译者，那我就再荣幸不过了。

**Comment by wxy** [comment]
> 是的，我只是提出对于未来翻译的一个大致的建议，并非针对某一个或几个具体的词语翻译 😂 LCTT 有些现定的翻译未必不比列出的那些落后于时代的审定术语翻译得好。
> 
> 如果能将这几个链接加入到翻译参考建议里、帮助到后来的其他翻译者，那我就再荣幸不过了。

您说的对，我建议您亲自将这些建议添加到我们的 wiki 中，您来提出 PR。

对于英文名词的翻译，我在之前的文章也有过一些文字说过我的想法。大致组织一下：

- 原则是能译尽量译，不建议使用中英文混杂的文字。
- 除了英文缩写，这个不需要翻译。不过如果有生僻的英文缩写，建议采用 RUBY 标签给出中英文的全称对照。
- 一些因袭的英文词汇，比如 Shell 这样的，确实贸然翻译会造成读者的普遍混淆，这种情况下要慎重。
- 一些不是特别普遍，或者比较生僻，可以尝试性去建立新的译法。这种情况下，国家审定的名称可以重点考虑，但是也不是必须遵循——因为国家审定的名词往往滞后发展。
- 一些新的，还没来得及翻译的英文词汇，可以首倡翻译。尤其是该词汇有了新的引申含义，可以考虑根据信达雅的原则创造新的词汇。

以上是我一些不成熟、也在不断完善的想法。供您及其它贡献者、读者参考。
