### ISSUE TITLE
[推荐选题] 20210205 Why simplicity is critical to delivering sturdy applications

### ISSUE THREAD

**Issue by toknow-gh** [LCTT/TranslateProject#28728]
### 原文链接地址

https://opensource.com/article/21/2/simplicity

### 版权协议

CC-SA-BY

### 文章难度

一般

### 文章分类

技术（tech）

### 推荐理由

是以下选题系列文章的后续文章
sources\tech\20210201 My handy guide to software development and testing.md
sources\tech\20210202 How I build and expand application development and testing.md
sources\tech\20210203 Defining boundaries and interfaces in software development.md
sources\tech\20210204 How to implement business requirements in software development.md

**Comment by wxy** [comment]
@toknow-gh 该系列前面的文章也没翻译，是你准备接手这个系列吗？

**Comment by toknow-gh** [comment]
@wxy 是的，我已经申领了第一篇

**Comment by wxy** [comment]
@lkxed

**Comment by lkxed** [comment]
@toknow-gh @wxy 已选
