### ISSUE TITLE
[推荐选题] 2023-11-01 Confusing git terminology

### ISSUE THREAD

**Issue by Dedicatus5457** [LCTT/TranslateProject#30408]
### 原文链接地址

https://jvns.ca/blog/2023/11/01/confusing-git-terminology/

### 版权协议

CC-SA-BY

### 文章难度

一般

### 文章分类

技术（tech）

### 推荐理由

解释了关于git的一些有歧义或难以理解的名词。

另外：这篇文章按照原作者的说明许可证是CC BY-NC-SA 4.0。详见: [原作者杂志的FAQ](https://wizardzines.com/faq/)

![image](https://github.com/LCTT/TranslateProject/assets/78254776/8041272f-5265-4bbe-a76a-c3001232bf10)

**Comment by wxy** [comment]
该站的文章会自动选入。此文已经选入，你可以申请翻译了~ #30404
