### ISSUE TITLE
[推荐选题] 20230727 AI: A Few More Useful Python Libraries

### ISSUE THREAD

**Issue by toknow-gh** [LCTT/TranslateProject#30416]
### 原文链接地址

https://www.opensourceforu.com/2023/07/ai-a-few-more-useful-python-libraries/

### 版权协议

CC-SA-BY

### 文章难度

容易

### 文章分类

技术（tech）

### 推荐理由

是 tech\20220629 AI- Some History and a Lot More about Matrices.md 的后续文章

**Comment by wxy** [comment]
请 @lujun9972 帮忙把这个系列选入。

**Comment by toknow-gh** [comment]
@lujun9972  以下是该系列全部文章链接。其中【1】【2】原来已经选入了。【3】是本次推荐的。

【1】  20220809    [Artificial Intelligence: Explaining the Basics](https://www.opensourceforu.com/2022/08/artificial-intelligence-explaining-the-basics/)
【2】  20220629    [AI: Some History and a Lot More about  Matrices](https://www.opensourceforu.com/2022/06/ai-some-history-and-a-lot-more-about-matrices/)
【3】  20230727    [AI: A Few More Useful Python Libraries](https://www.opensourceforu.com/2023/07/ai-a-few-more-useful-python-libraries/)
【4】  20230102    [AI: An Introduction to Probability](https://www.opensourceforu.com/2023/01/ai-an-introduction-to-probability/)
【5】  20221228    [AI: Anaconda and More on Probability](https://www.opensourceforu.com/2022/12/ai-anaconda-and-more-on-probability/)
【6】  20230116    [AI: Introduction to Keras and Our First Data Set](https://www.opensourceforu.com/2023/01/ai-introduction-to-keras-and-our-first-data-set/)
【7】  20230208    [AI: An Introduction to Scikit-learn and Our First Trained Model](https://www.opensourceforu.com/2023/02/ai-an-introduction-to-scikit-learn-and-our-first-trained-model/)
【8】  20230301    [AI: More About Neural Networks and an Introduction to PyTorch](https://www.opensourceforu.com/2023/03/ai-more-about-neural-networks-and-an-introduction-to-pytorch/)
【9】  20230417    [AI: An Introduction to Natural Language Processing](https://www.opensourceforu.com/2023/04/ai-an-introduction-to-natural-language-processing/)
【10】 20230515    [AI: Introduction to Computer Vision](https://www.opensourceforu.com/2023/05/ai-introduction-to-computer-vision/)
【11】 20230626    [AI: Classical Techniques and Hidden Python Gems](https://www.opensourceforu.com/2023/06/ai-classical-techniques-and-hidden-python-gems/)
【12】 20230710    [AI: Beyond Python](https://www.opensourceforu.com/2023/07/ai-beyond-python/)

**Comment by wxy** [comment]
@toknow-gh 根据了解，opensourceforu 从 2018 年 6 月后就删除了其 CC-BY 授权，所以，这个系列的文章无法再继续通过 LCTT/TranslatedProject 来翻译了。

**Comment by toknow-gh** [comment]
已获得作者授权 https://github.com/LCTT/TranslateProject/issues/8562#issuecomment-1807004574 ，请选题帮忙选入一下 @lujun9972 @wxy

**Comment by wxy** [comment]
> 已获得作者授权 [#8562 (comment)](https://github.com/LCTT/TranslateProject/issues/8562#issuecomment-1807004574) ，请选题帮忙选入一下 @lujun9972 @wxy

@toknow-gh ，@lujun9972 已经帮你选好了。
