### ISSUE TITLE
沟通工具的推荐

### ISSUE THREAD

**Issue by yuanbohan** [LCTT/TranslateProject#3947]
hi support,

非常欣喜看到有这么一个优秀的团队，从国外优秀媒体那里翻译 Linux 相关的技术、资讯、杂文等内容。

看到小组还在使用 QQ 来进行项目的沟通和推动，希望 bearychat.com 能够帮助到小组提升沟通效率，将各项目整理的有条不紊。

附：
这里是一篇真实团队的使用场景 [像 SwiftGG 翻译组那样使用 BearyChat](http://bearyinnovative.com/swiftgg/)

**Comment by Vic020** [comment]
@wxy  新状况啊,这种友好的推广,是什么态度呢?

**Comment by oska874** [comment]
@Vic020 友好的回复谢谢，然后close issue。
