### ISSUE TITLE
译者链接错误

### ISSUE THREAD

**Issue by pengkai** [LCTT/TranslateProject#4021]
https://github.com/LCTT/TranslateProject/blob/f6c54b796ca0ac211a7fe46adc2d526d650159ac/published/20160225%20How%20to%20add%20open%20source%20experience%20to%20your%20resume.md

这篇文章译者的链接错了，链到我这来了。

**Comment by oska874** [comment]
这篇不是你翻译的？

**Comment by mudongliang** [comment]
我当时在 history 里面看见你的名字,所以就把你加上去了

**Comment by wxy** [comment]
应该是 @kylepeng93 翻译的。没留译者。。我更正一下。
