### ISSUE TITLE
选题：A Web Crawler With asyncio Coroutines

### ISSUE THREAD

**Issue by qingyunha** [LCTT/TranslateProject#4378]
原文在这 http://aosabook.org/en/500L/pages/a-web-crawler-with-asyncio-coroutines.html
译文在这 http://qingyunha.github.io/hugo/translation/crawler/
如果你们觉得可以的话，我会提个PR :smile:

**Comment by Vic020** [comment]
@wxy

**Comment by Vic020** [comment]
@oska874

**Comment by oska874** [comment]
@qingyunha ok，你提pr吧。
大标题和小标题都翻译了，咱么的格式添加小尾巴就行了

**Comment by wxy** [comment]
然后呢？
