### ISSUE TITLE
请求添加选题～

### ISSUE THREAD

**Issue by name1e5s** [LCTT/TranslateProject#5656]
http://www.washingtonpost.com/sf/business/2015/11/05/net-of-insecurity-the-kernel-of-the-argument/?utm_term=.0d921b8fff97

**Comment by wxy** [comment]
@name1e5s 这篇的消息已经过时，而且我们发过另外一篇相关的 https://linux.cn/article-7404-1.html

**Comment by name1e5s** [comment]
谢谢组长～
