### ISSUE TITLE
[选题推荐] 最早进行游戏设计与开发的女程序员上世纪七十年代她高中毕业后作为合同工独立给游戏主机Studio II 开发了几款游戏后来这款游戏主机卖得不好就没再继续开发了就去读大学了 https://t.co/W0AwUAhyLv

### ISSUE THREAD

**Issue by lctt-new** [LCTT/TranslateProject#6236]
https://t.co/W0AwUAhyLv &#65288;&#21491;&#38190;&#26032;&#31383;&#21475;&#25171;&#24320;&#25105;&#65289;<br><br>
@oska874<br>
November 09, 2017 at 03:19PM via Twitter

**Comment by wxy** [comment]
这个意义也不大
