### ISSUE TITLE
[选题推荐] How to Improve a Legacy Codebase几乎每个工程师职业生涯里都会有接手别人留下的烂摊子烂代码的经历到处是地雷该如何改进很简单也很重要的规则一次只改一个地方 https://t.co/fy7FAPC9tQ

### ISSUE THREAD

**Issue by lctt-new** [LCTT/TranslateProject#6237]
https://t.co/fy7FAPC9tQ &#65288;&#21491;&#38190;&#26032;&#31383;&#21475;&#25171;&#24320;&#25105;&#65289;<br><br>
@oska874<br>
November 09, 2017 at 03:45PM via Twitter

**Comment by wxy** [comment]
https://jacquesmattheij.com/improving-a-legacy-codebase 原文地址
