### ISSUE TITLE
[选题推荐] Linux Shell Scripting: A Project-Based Approach to Learning
 https://t.co/UZQMwoKg70

#Cisco #AWS #ComptiA https://t.co/8zpmFg4BMK

### ISSUE THREAD

**Issue by lctt-new** [LCTT/TranslateProject#6241]
https://t.co/UZQMwoKg70 &#65288;&#21491;&#38190;&#26032;&#31383;&#21475;&#25171;&#24320;&#25105;&#65289;<br><br>
@oska874<br>
November 10, 2017 at 07:50PM via Twitter

**Comment by wxy** [comment]
这不是一篇文章  /cry
