### ISSUE TITLE
[选题推荐] Build Ajax Web Apps with Laravel 5.2 Bootstrap and jQuery
 https://t.co/2N6lfshsdq

#Cisco #AWS #ComptiA https://t.co/W2Ywfuib2R

### ISSUE THREAD

**Issue by lctt-new** [LCTT/TranslateProject#6242]
https://t.co/2N6lfshsdq &#65288;&#21491;&#38190;&#26032;&#31383;&#21475;&#25171;&#24320;&#25105;&#65289;<br><br>
@oska874<br>
November 10, 2017 at 12:01AM via Twitter

**Comment by wxy** [comment]
这不是一篇文章
