### ISSUE TITLE
[选题推荐] New Linux support lets users program their Linux devices as if they were regular Arduinos: https://t.co/KwBVm3avGB https://t.co/5wXectDd32

### ISSUE THREAD

**Issue by lctt-new** [LCTT/TranslateProject#6243]
https://t.co/KwBVm3avGB &#65288;&#21491;&#38190;&#26032;&#31383;&#21475;&#25171;&#24320;&#25105;&#65289;<br><br>
@oska874<br>
November 10, 2017 at 05:02PM via Twitter

**Comment by wxy** [comment]
这篇也价值不大
