### ISSUE TITLE
[选题推荐] The Life-Changing Magic of Tidying Up Code极限编程之父Kent Beck现在FB工作分享清理代码的心得悠着点别太较真发现自己被带进坑里了就赶紧revert代码别纠缠了 https://t.co/XU0ShHk2HY

### ISSUE THREAD

**Issue by lctt-new** [LCTT/TranslateProject#6247]
https://t.co/XU0ShHk2HY &#65288;&#21491;&#38190;&#26032;&#31383;&#21475;&#25171;&#24320;&#25105;&#65289;<br><br>
@oska874<br>
November 12, 2017 at 07:16AM via Twitter

**Comment by wxy** [comment]
源链： https://www.facebook.com/notes/kent-beck/the-life-changing-magic-of-tidying-up-code/1544047022294823/
