### ISSUE TITLE
[选题推荐] AWS Machine Learning: A Complete Guide With Python
 https://t.co/JxB7VTlE5I

#Cisco #AWS #ComptiA #MicrosoftAzure https://t.co/I2SLS8Htro

### ISSUE THREAD

**Issue by lctt-new** [LCTT/TranslateProject#6249]
https://t.co/JxB7VTlE5I &#65288;&#21491;&#38190;&#26032;&#31383;&#21475;&#25171;&#24320;&#25105;&#65289;<br><br>
@oska874<br>
November 12, 2017 at 07:59PM via Twitter

**Comment by wxy** [comment]
这不是文章
