### ISSUE TITLE
[选题推荐] Configuration is key to a successful installation of NixOS: https://t.co/TzwHb3e4oP https://t.co/4wsErFPnZ2

### ISSUE THREAD

**Issue by lctt-new** [LCTT/TranslateProject#6250]
https://t.co/TzwHb3e4oP &#65288;&#21491;&#38190;&#26032;&#31383;&#21475;&#25171;&#24320;&#25105;&#65289;<br><br>
@oska874<br>
November 12, 2017 at 10:02PM via Twitter

**Comment by oska874** [comment]
重复
