### ISSUE TITLE
[选题推荐] 68% of businesses are struggling to hire talent for #IoT! https://t.co/LsCkrqNNAu https://t.co/odXJAQTCUc

### ISSUE THREAD

**Issue by lctt-new** [LCTT/TranslateProject#6251]
https://t.co/LsCkrqNNAu &#65288;&#21491;&#38190;&#26032;&#31383;&#21475;&#25171;&#24320;&#25105;&#65289;<br><br>
@oska874<br>
November 12, 2017 at 06:22PM via Twitter

**Comment by wxy** [comment]
这是个信息图，不适合做文章
