### ISSUE TITLE
[选题推荐] System logs are incredibly important files in Linux. Learn about the results &amp; solutions to complement your Getting Started with Linux magazine - https://t.co/B8BDbfSsGp

### ISSUE THREAD

**Issue by lctt-new** [LCTT/TranslateProject#6299]
https://t.co/B8BDbfSsGp &#65288;&#21491;&#38190;&#26032;&#31383;&#21475;&#25171;&#24320;&#25105;&#65289;<br><br>
@oska874<br>
November 20, 2017 at 06:10PM via Twitter

**Comment by qhwdw** [comment]
https://www.suse.com/communities/blog/system-logs-understand-linux-system/
