### ISSUE TITLE
[选题推荐] Linux has several open-source programs for drawing image editing design &amp; more. Programs like GIMP InkScape and Okular make the move to Linux simple - https://t.co/i7wkU0ylJs

### ISSUE THREAD

**Issue by lctt-new** [LCTT/TranslateProject#6300]
https://t.co/i7wkU0ylJs &#65288;&#21491;&#38190;&#26032;&#31383;&#21475;&#25171;&#24320;&#25105;&#65289;<br><br>
@oska874<br>
November 20, 2017 at 09:13PM via Twitter

**Comment by qhwdw** [comment]
https://www.suse.com/communities/blog/unleash-creativity-linux-programs-drawing-image-editing/
