### ISSUE TITLE
[选题推荐] Inspiring the Next Generation of Open Source https://t.co/PnqhusPVZ5

### ISSUE THREAD

**Issue by lctt-new** [LCTT/TranslateProject#6308]
https://t.co/PnqhusPVZ5 &#65288;&#21491;&#38190;&#26032;&#31383;&#21475;&#25171;&#24320;&#25105;&#65289;<br><br>
@oska874<br>
November 23, 2017 at 01:01AM via Twitter

**Comment by oska874** [comment]
视频不好处理啊

**Comment by qhwdw** [comment]
https://www.linux.com/news/inspiring-next-generation-open-source
