### ISSUE TITLE
[选题推荐] The demand for security professionals is real; get details in the Open Source Jobs Report from Dice and The Linux Foundation: https://t.co/HvjCqI9bo4 https://t.co/ioBLvJELPN

### ISSUE THREAD

**Issue by lctt-new** [LCTT/TranslateProject#6310]
https://t.co/HvjCqI9bo4 &#65288;&#21491;&#38190;&#26032;&#31383;&#21475;&#25171;&#24320;&#25105;&#65289;<br><br>
@oska874<br>
November 23, 2017 at 07:18AM via Twitter

**Comment by qhwdw** [comment]
https://www.linux.com/blog/os-jobs-report/2017/11/security-jobs-are-hot-get-trained-and-get-noticed
