### ISSUE TITLE
[选题推荐] Did you know that 48% of people are unaware that their #IoT devices pose a security threat? Read more --&gt; https://t.co/jWEenTySm3 https://t.co/Sld85Prn7X

### ISSUE THREAD

**Issue by lctt-new** [LCTT/TranslateProject#6324]
https://t.co/jWEenTySm3 &#65288;&#21491;&#38190;&#26032;&#31383;&#21475;&#25171;&#24320;&#25105;&#65289;<br><br>
@oska874<br>
November 25, 2017 at 01:15AM via Twitter

**Comment by qhwdw** [comment]
https://pages.ubuntu.com/IoT-Security-whitepaper.html?utm_source=Twitter&utm_medium=Social&utm_campaign=FY18_IOT_UbuntuCore_SecurityWhitepaper

**Comment by oska874** [comment]
pdf 有点长
