### ISSUE TITLE
[选题推荐] New Year's resolution: 1) Rock free #Linux swag 2) Get open source certified. Our #BlackFriday sale will check both of these off with certification bundles at 60% off! Info: https://t.co/U4DzBssiCp https://t.co/vgon54D70m

### ISSUE THREAD

**Issue by lctt-new** [LCTT/TranslateProject#6331]
https://t.co/U4DzBssiCp &#65288;&#21491;&#38190;&#26032;&#31383;&#21475;&#25171;&#24320;&#25105;&#65289;<br><br>
@oska874<br>
November 25, 2017 at 01:33AM via Twitter

**Comment by qhwdw** [comment]
https://www2.thelinuxfoundation.org/blackfridaydeals2017

**Comment by oska874** [comment]
???
