### ISSUE TITLE
[选题推荐] #Learn how to use #Ansible at this week's Fedora Classroom: https://t.co/PyHQjgq3P8 #automate #simplify

### ISSUE THREAD

**Issue by lctt-new** [LCTT/TranslateProject#6382]
https://t.co/PyHQjgq3P8 &#65288;&#21491;&#38190;&#26032;&#31383;&#21475;&#25171;&#24320;&#25105;&#65289;<br><br>
@oska874<br>
November 29, 2017 at 01:21AM via Twitter

**Comment by qhwdw** [comment]
https://fedoramagazine.org/fedora-classroom-session-ansible-101/
