### ISSUE TITLE
[选题推荐] Check out Photon OS a Linux distro geared specifically for the purpose of deploying containers: https://t.co/Ovz7KF7WJX https://t.co/HyItYCKgjb

### ISSUE THREAD

**Issue by lctt-new** [LCTT/TranslateProject#6383]
https://t.co/Ovz7KF7WJX &#65288;&#21491;&#38190;&#26032;&#31383;&#21475;&#25171;&#24320;&#25105;&#65289;<br><br>
@oska874<br>
November 29, 2017 at 04:19AM via Twitter

**Comment by qhwdw** [comment]
https://www.linux.com/learn/intro-to-linux/2017/11/photon-could-be-your-new-favorite-container-os
