### ISSUE TITLE
[选题推荐] Inside AGL: Familiar Open Source Components Ease Learning Curve https://t.co/jwEeoDwpSQ

### ISSUE THREAD

**Issue by lctt-new** [LCTT/TranslateProject#6389]
https://t.co/jwEeoDwpSQ &#65288;&#21491;&#38190;&#26032;&#31383;&#21475;&#25171;&#24320;&#25105;&#65289;<br>
<br>
@oska874<br>
November 29, 2017 at 10:31PM via Twitter

**Comment by qhwdw** [comment]
https://www.linux.com/blog/event/elce/2017/11/inside-agl-familiar-open-source-components-ease-learning-curve
