### ISSUE TITLE
[选题推荐] Getting started with Hadoop Spark https://t.co/JjvKbLcPFq #JujuCharms #BigData #Tutorial https://t.co/7kv3KmvxoA

### ISSUE THREAD

**Issue by lctt-new** [LCTT/TranslateProject#6391]
https://t.co/JjvKbLcPFq &#65288;&#21491;&#38190;&#26032;&#31383;&#21475;&#25171;&#24320;&#25105;&#65289;<br>
<br>
@oska874<br>
November 30, 2017 at 02:17AM via Twitter

**Comment by qhwdw** [comment]
https://tutorials.ubuntu.com/tutorial/get-started-hadoop-spark
