### ISSUE TITLE
[选题推荐] Wake up and Shut Down Linux Automatically https://t.co/aanZRsWo3t

### ISSUE THREAD

**Issue by lctt-new** [LCTT/TranslateProject#6409]
https://t.co/aanZRsWo3t &#65288;&#21491;&#38190;&#26032;&#31383;&#21475;&#25171;&#24320;&#25105;&#65289;<br>
<br>
@oska874<br>
November 30, 2017 at 10:15PM via Twitter

**Comment by qhwdw** [comment]
https://www.linux.com/learn/intro-to-linux/2017/11/wake-and-shut-down-linux-automatically
