### ISSUE TITLE
[选题推荐] How to Manage Users with Groups in Linux https://t.co/qLPzcf7zeJ

### ISSUE THREAD

**Issue by lctt-new** [LCTT/TranslateProject#6410]
https://t.co/qLPzcf7zeJ &#65288;&#21491;&#38190;&#26032;&#31383;&#21475;&#25171;&#24320;&#25105;&#65289;<br>
<br>
@oska874<br>
December 01, 2017 at 11:02PM via Twitter

**Comment by qhwdw** [comment]
https://www.linux.com/learn/intro-to-linux/2017/12/how-manage-users-groups-linux
