### ISSUE TITLE
[选题推荐] Kubeflow: Bringing Together Kubernetes and Machine Learning https://t.co/TA5bPusR7c

### ISSUE THREAD

**Issue by lctt-new** [LCTT/TranslateProject#6603]
https://t.co/TA5bPusR7c &#65288;&#21491;&#38190;&#26032;&#31383;&#21475;&#25171;&#24320;&#25105;&#65289;<br>
<br>
@oska874<br>
December 12, 2017 at 10:48PM via Twitter

**Comment by lujun9972** [comment]
这个只有部分内容，全文链接打不开
