### ISSUE TITLE
[选题推荐] GeckoLinux is a unique distro that offers some options openSUSE does not. Jack Wallen takes a look: https://t.co/IGCa4gYhDl https://t.co/nXaa41JBgB

### ISSUE THREAD

**Issue by lctt-new** [LCTT/TranslateProject#6608]
https://t.co/IGCa4gYhDl &#65288;&#21491;&#38190;&#26032;&#31383;&#21475;&#25171;&#24320;&#25105;&#65289;<br>
<br>
@oska874<br>
December 13, 2017 at 08:23PM via Twitter

**Comment by wxy** [comment]
https://www.linux.com/learn/intro-to-linux/2017/12/geckolinux-brings-flexibility-and-choice-opensuse

**Comment by lujun9972** [comment]
已经选过了
