### ISSUE TITLE
[选题推荐] Mining cryptocurrency with Raspberry Pi and Storj - https://t.co/IpsCzzYCce: Storj uses a proof-of-retrievability system allowing users "rent out" spare disk space and get paid monthly in Storj coin. https://t.co/vxS8bs7hPz

### ISSUE THREAD

**Issue by lctt-new** [LCTT/TranslateProject#6611]
https://t.co/IpsCzzYCce &#65288;&#21491;&#38190;&#26032;&#31383;&#21475;&#25171;&#24320;&#25105;&#65289;<br>
<br>
@oska874<br>
December 13, 2017 at 10:31PM via Twitter

**Comment by lujun9972** [comment]
这个链接好像有问题？打开来是https://opensource.com/

**Comment by wxy** [comment]
https://opensource.com/article/17/12/raspberry-pi-cryptocurrency-mining
