### ISSUE TITLE
[选题推荐] Rereading this cool #RaspberryPi guide via @swapnilbhartiya: https://t.co/UqBqHweVSM Anyone else feeling a fun project coming on?

### ISSUE THREAD

**Issue by lctt-new** [LCTT/TranslateProject#6670]
https://t.co/UqBqHweVSM &#65288;&#21491;&#38190;&#26032;&#31383;&#21475;&#25171;&#24320;&#25105;&#65289;<br>
<br>
@oska874<br>
December 15, 2017 at 07:56AM via Twitter

**Comment by oska874** [comment]
https://www.infoworld.com/article/3176488/linux/a-beginner-s-guide-to-raspberry-pi-3.html
