### ISSUE TITLE
[选题推荐] The Best Linux App &amp; Distro Releases of 2017 https://t.co/BoqrVw24m1 https://t.co/pkKEC4LFMZ

### ISSUE THREAD

**Issue by lctt-new** [LCTT/TranslateProject#6675]
https://t.co/BoqrVw24m1 &#65288;&#21491;&#38190;&#26032;&#31383;&#21475;&#25171;&#24320;&#25105;&#65289;<br>
<br>
@oska874<br>
December 14, 2017 at 09:19PM via Twitter

**Comment by oska874** [comment]
http://www.omgubuntu.co.uk/2017/12/list-best-linux-distros-apps-2017
