### ISSUE TITLE
[选题推荐] 6 open source home automation tools - https://t.co/IpsCzzYCce: Turn your home into a smart home with these open source software solutions. https://t.co/OUD7REqaah

### ISSUE THREAD

**Issue by lctt-new** [LCTT/TranslateProject#6676]
https://t.co/IpsCzzYCce &#65288;&#21491;&#38190;&#26032;&#31383;&#21475;&#25171;&#24320;&#25105;&#65289;<br>
<br>
@oska874<br>
December 15, 2017 at 03:30PM via Twitter

**Comment by oska874** [comment]
链接有问题

**Comment by oska874** [comment]
https://opensource.com/life/17/12/home-automation-tools

**Comment by lujun9972** [comment]
已经选过了
