### ISSUE TITLE
PR 的 CI 文件名检查规则更新

### ISSUE THREAD

**Issue by wxy** [LCTT/TranslateProject#6692]
根据用例，PR 中提交的文件名的规范（PREG）如下：

`/^\d{6} [a-z0-9\.,!\?\(\)\[\]‘“_ -]+\.md$/i`

此外，选题工具生成文件名时也应该遵循此规则，对于非此集合内的字符，转换为“-” 或空格 即可。
@vizv @bestony @oska874 @lujun9972

**Comment by lujun9972** [comment]
在[]里似乎不需要用\来做转义？

**Comment by oska874** [comment]
?!":|\/*<> 这几个不能用

**Comment by wxy** [comment]
嗯，`?` 会做单位通配，`"` 呢？`!` 呢？

**Comment by oska874** [comment]
这几个windows都不支持
