### ISSUE TITLE
Linux中国术语词典中orchestration翻译有误

### ISSUE THREAD

**Issue by wffger** [LCTT/TranslateProject#6715]
你好，根据[编配和编排的定义之争](http://www.infoq.com/cn/news/2008/09/Orchestration?utm_medium=link&utm_campaign=BPEL)，”orchestration“翻译成”编配“更为恰当。

**Comment by wxy** [comment]
这个讨论值得参考。但是目前的现状是，choreography 在容器相关的领域用的较少，而编配一词几乎罕见与容器领域。这似乎已经形成了既有的错误共识。

**Comment by wffger** [comment]
翻译人有义务也有责任对每一个词组做到严谨准确地翻译，特别是汉语翻译，更加要做到严谨准确细致。这个问题起源原本只是英语的定义之争，但是目前网上的相关讨论大多将orchestration翻译成“编排”，不仅无益于技术探讨，模糊的中文翻译对技术思想传播更是有害。如果是翻译有误，我相信LCTT有能力纠正这个错误。

**Comment by wxy** [comment]
我会在 LCTT 发起讨论看看
