### ISSUE TITLE
[选题推荐] Did you know GNOME Builder has built in debugging support? Learn the basics of debugging in Builder with this primer on the Fedora Magazine https://t.co/8yMXYIguIN

### ISSUE THREAD

**Issue by lctt-new** [LCTT/TranslateProject#6778]
https://t.co/8yMXYIguIN &#65288;&#21491;&#38190;&#26032;&#31383;&#21475;&#25171;&#24320;&#25105;&#65289;<br>
<br>
@oska874<br>
December 20, 2017 at 07:06PM via Twitter

**Comment by oska874** [comment]
https://fedoramagazine.org/debugging-gnome-builder/
