### ISSUE TITLE
[选题推荐] Getting started with @golang? @GoLandIDE IDE makes it easy with on-the-fly code checking smart auto-completion and integrated debugger

snap install goland --classic 

https://t.co/vSRnFNBBwG https://t.co/qP9SChVrdy

### ISSUE THREAD

**Issue by lctt-new** [LCTT/TranslateProject#6780]
https://t.co/vSRnFNBBwG &#65288;&#21491;&#38190;&#26032;&#31383;&#21475;&#25171;&#24320;&#25105;&#65289;<br>
<br>
@oska874<br>
December 26, 2017 at 11:06PM via Twitter

**Comment by oska874** [comment]
https://snapcraft.io/goland/
