### ISSUE TITLE
选题申请：Formalizing dynamic scoping

### ISSUE THREAD

**Issue by lujun9972** [LCTT/TranslateProject#7317]
https://www.stephanboyer.com/post/124/formalizing-dynamic-scoping

**Comment by wxy** [comment]
这没啥问题啊，直接选好了~

**Comment by lujun9972** [comment]
问题是那一堆公式好像转不下来…

**Comment by wxy** [comment]
公式这样，你原文中标明，让发布者（即我）做截图好了。
