### ISSUE TITLE
[选题推荐]Have a Laugh With Funny Linux Man Pages

### ISSUE THREAD

**Issue by oska874** [LCTT/TranslateProject#8015]
https://itsfoss.com/funny-man-pages/

**Comment by lujun9972** [comment]
没有版权，不过我已经把它改写了
https://github.com/lujun9972/lujun9972.github.com/blob/source/linux%E5%92%8C%E5%AE%83%E7%9A%84%E5%B0%8F%E4%BC%99%E4%BC%B4/funny-manpages.org

**Comment by oska874** [comment]
@wxy ，可以联系这个网站，看能不能翻译。看看LF能帮上忙不。
