### ISSUE TITLE
联系作者确认可以翻译的网站

### ISSUE THREAD

**Issue by oska874** [LCTT/TranslateProject#8562]
www.jtolio.com
dave.cheney.net
itsfoss.com

**Comment by oska874** [comment]
nicolasparada.netlify.com

**Comment by oska874** [comment]
jvns.ca
（需要声明非官方翻译）

**Comment by lujun9972** [comment]
除了mintguide.org的RSS需要翻墙访问之外，其他的网站都已加入自动选题套餐。

**Comment by oska874** [comment]
itsfoss license
![image](https://github.com/LCTT/TranslateProject/assets/4536559/944fca2d-033e-4f31-9352-82154374bfea)

**Comment by oska874** [comment]
jvns.ca license
![image](https://github.com/LCTT/TranslateProject/assets/4536559/696c719f-8b22-42c8-924e-52cb1a99cb01)

**Comment by toknow-gh** [comment]
license of  [Deepu Benson](https://www.opensourceforu.com/author/deepu-benson/)

![ license of  Deepu Benson](https://github.com/LCTT/TranslateProject/assets/8038013/81f03549-af6e-4310-a9c7-9350b1c954b9)
