### ISSUE TITLE
翻译的原文中本身有错误

### ISSUE THREAD

**Issue by no1xsyzy** [LCTT/TranslateProject#8841]
GitHub : [published/20180417 How to do math on the Linux command line.md](https://github.com/LCTT/TranslateProject/blob/c0be9c243dc148ef78af1e2e0bf814503e1daa50/published/20180417%20How%20to%20do%20math%20on%20the%20Linux%20command%20line.md)
LXCN : [Linux 命令行下的数学运算 https://linux.cn/article-9642-1.html](https://linux.cn/article-9642-1.html)

1. `expr` 段落中，用了 `expr "11" = "11"` 来举字符串比较的例子，但实际上大部分 Shell，包括 Bash 和 dash，引号具有语义，这样运行在 `exec` 的时候是不存在引号的。 `expr "11" = "011"` 也会返回 1，只有写成 `expr '"11"' = '"011"'` 才返回 0。
2. 在“简单的 bash 数学运算”一节，例子是对的，用了 `**` 当幂运算符号，但后面说
   > `^       指数运算`

   这就不对了，`^` 表示的是“按位异或”。
3. 没有关于**为什么**星号（`*`）前加反斜杠（`\`）的说明。“防止语法错误”是你做了**什么**，“加反斜杠”是你**如何**做到这件事的，而“星号是匹配对于当前活动目录所有文件的通配符”并且“反斜杠阻止了这一行为”是**为什么**这么做。只有谈到**为什么**才能让读者更好地明白 Shell。在后面甚至完全没有 `>` 前加反斜杠的任何描述。

另外，也已向原文通过 Facebook 提出：
> 1. in example of expr there shows `expr "11" = "11"` as a comparison between strings, but in most shells like bash or dash, " is used to mark boundary of argv's, so they are not interpreted as string. for illustration, `expr "11" = "011"` will also return true
> You MUST write `expr '"11"' = '"011"'` to get a false.
> 2. in "easy bash math" section, the code in example is good: ((e=e**2)), that is exponent, however, you then said `^		Get exponent`. ^ is NOT for exponent, but for bit-wise XOR. ** is the correct sign for exponent.
> 3. there is no description about WHY asterisk (`*`) cannot be there without an backslash (`\`). "avoid the syntax error" is WHAT you do, "adding a backslash" is HOW you do it, and "asterisk is a glob to all files in current working directory" and "backslash prevents this behavior" is WHY you do it. Only to the WHY part can you let your reader know better about the shell. To make matters worse there is even no explanation about "`>`" sign.

**Comment by wxy** [comment]
谢谢您的指正，我来看看看如何修正。

**Comment by no1xsyzy** [comment]
> 如果将数字放到引号中间，那么你将进行字符串比较，而不是数值比较。

这一行和下面的4行例子一并删去比较好吧……一来例子还是没有意义的，二来比较容易混淆，要说清楚基本上是要把 Shell 的引号使用说一遍了。

----

当然真想要说清楚也可以，但未免冗余，不妨找一个外部链接？或者以前的文章？

**Comment by wxy** [comment]
@no1xsyzy 确实是，画蛇添足了，删除比较好。
