### ISSUE TITLE
文章是怎样转换称 markdown 格式的？

### ISSUE THREAD

**Issue by MjSeven** [LCTT/TranslateProject#8843]
外文是如何成 markdown 格式的？感兴趣想了解一下。
有些 sources 中的文章会将原文中两侧的相关链接加入，有时还会多一些无关内容。
所以想请教一下。

**Comment by wxy** [comment]
这个你可以和 @lujun9972 聊聊，也欢迎加入选题组。

**Comment by oska874** [comment]
选择文章内容，然后复制（拖动）到 http://lctt.ixiqin.com/ ，最后再手工做调整，你可以试试 @MjSeven

**Comment by lujun9972** [comment]
我一般用python的newspaper库先抽出主要内容，再做转换

**Comment by MjSeven** [comment]
那个网站很赞啊，Python 的库也不错，我完了试一下
