### ISSUE TITLE
网页格式错误

### ISSUE THREAD

**Issue by no1xsyzy** [LCTT/TranslateProject#8928]
文章页面：<https://linux.cn/article-9681-1.html>
网页效果如图：
![image](https://user-images.githubusercontent.com/7346170/40574305-edcb1922-6101-11e8-9d52-2be7a2a68d74.png)

估计是[第261行附近(只找到blame可以显示md的行数)](https://github.com/LCTT/TranslateProject/blame/68d5215c9ac2277e9720511bb78cbb2e31307b32/published/20180327%20Loop%20better-%20A%20deeper%20look%20at%20iteration%20in%20Python.md#L261)代码分界线问题。

**Comment by wxy** [comment]
谢谢，已修正。
