### ISSUE TITLE
请求更新 Linux From Scratch 到最新版本

### ISSUE THREAD

**Issue by ZeroAurora** [LCTT/TranslateProject#9014]
已翻译版本 7.7 发布于2015年3月6日。
最新版 8.2 发布于2018年3月2日，时隔3年。

**Comment by wxy** [comment]
@martin2011qi @dongfengweixiao @vizv

**Comment by martin2011qi** [comment]
LFS 手册的翻译问题请移步 [LCTT/LFS-BOOK](https://github.com/LCTT/LFS-BOOK) 当前版本是 8.0。

**Comment by ZeroAurora** [comment]
好的，抱歉打扰

**Comment by vizv** [comment]
@ZeroAurora 源码已更新至 8.2，欢迎协助移植
