### ISSUE TITLE
选题文章列表

### ISSUE THREAD

**Issue by oska874** [LCTT/TranslateProject#9476]
文章列表，感兴趣的@我，qq群里也可以。然后我们再给你选题、翻译。
（本issue 仅供选题和申领使用）

**Comment by oska874** [comment]
Javascript Framework Comparison with Examples (React, Vue & Hyperapp)
https://hackernoon.com/javascript-framework-comparison-with-examples-react-vue-hyperapp-97f064fb468d

The Extensive Guide to Creating Streams in RxJS
https://blog.angularindepth.com/the-extensive-guide-to-creating-streams-in-rxjs-aaa02baaff9a

What is JSX?
https://blog.kentcdodds.com/what-is-jsx-310ab98c463e

**Comment by oska874** [comment]
Using MongoDB as a realtime database with change streams
https://hackernoon.com/using-mongodb-as-a-realtime-database-with-change-streams-213cba1dfc2a

Best Practices for Cassandra Data Modeling
https://dzone.com/articles/best-practices-for-cassandra-data-modeling

**Comment by oska874** [comment]
Python

Computability, Complexity, & Algorithms Part 1
http://kldavenport.com/algorithm-complexity-part-1/

Python Sets: What, Why and How
https://www.pythoncheatsheet.org/blog/python-sets-what-why-how

[PyNg] A Simple Anomaly Detection Algorithm
https://medium.com/@mathmare_/pyng-a-simple-anomaly-detection-algorithm-2f355d7dc054

Understanding Python Dataclasses — Part 1
https://medium.com/mindorks/understanding-python-dataclasses-part-1-c3ccd4355c34

**Comment by oska874** [comment]
GoLang & web

Slices from the ground up
https://dave.cheney.net/2018/07/12/slices-from-the-ground-up

Open API with Go Part 1 - Introduction
https://posener.github.io/openapi-intro/

Go WebAssembly: Binding structures to JS references
https://medium.zenika.com/go-webassembly-binding-structures-to-js-references-4eddd6fd4d23

USING GO (GOLANG) FOR WEBASSEMBLY APPLICATIONS
https://sebastian-holstein.de/post/2018-07-05-go-wasm-application/

You are going to need it — Using Interfaces and Dependency Injection to future proof your designs
https://medium.com/dm03514-tech-blog/you-are-going-to-need-it-using-interfaces-and-dependency-injection-to-future-proof-your-designs-2cf6f58db192

**Comment by oska874** [comment]
Web

Minimal Ubuntu, on public clouds and Docker Hub
https://blog.ubuntu.com/2018/07/09/minimal-ubuntu-released

Goodbye Microservices: From 100s of problem children to 1 superstar
https://segment.com/blog/goodbye-microservices/

Kotlin on the server at Khan Academy
http://engineering.khanacademy.org/posts/kotlin-adoption.htm

Serverless Performance: Cloudflare Workers, Lambda and Lambda@Edge
https://blog.cloudflare.com/serverless-performance-comparison-workers-lambda/

Amazon RDS Performance Insights is now generally available
https://aws.amazon.com/cn/blogs/database/amazon-rds-performance-insights-is-now-generally-available/

**Comment by oska874** [comment]
Node

Testing Node.js in 2018
https://hackernoon.com/testing-node-js-in-2018-10a04dd77391

Using AWS Lambda & Node.js to scan your S3 uploads
https://blog.truework.com/2018-07-09-s3-antivirus-lambda-function/

Twitter Sentiment Analysis using NodeJS
https://boostlog.io/@anshulc95/twitter-sentiment-analysis-using-nodejs-5ad1331247018500491f3b6a

**Comment by oska874** [comment]
Linux

Clear Linux Makes a Strong Case for Your Next Cloud Platform
https://www.linux.com/learn/intro-to-linux/2018/7/clear-linux-makes-strong-case-your-next-cloud-platform

netdev day 1: IPsec!
https://jvns.ca/blog/2018/07/11/netdev-day-1--ipsec/

netdev day 2: moving away from "as fast as possible" in networking code
https://jvns.ca/blog/2018/07/12/netdev-day-2--moving-away-from--as-fast-as-possible/


A sysadmin's guide to SELinux: 42 answers to the big questions
https://opensource.com/article/18/7/sysadmin-guide-selinux

Becoming a senior developer: 9 experiences you'll encounter
https://www.hpe.com/us/en/insights/articles/becoming-a-senior-developer-9-experiences-youll-encounter-1807.html

How I use Wireshark
https://jvns.ca/blog/2018/06/19/what-i-use-wireshark-for/

The return of Spectre
https://www.zdnet.com/article/the-return-of-spectre/

Container Adoption Starts to Outpace DevOps
https://containerjournal.com/2018/07/10/container-adoption-starts-to-outpace-devops/?platform=hootsuite

A sysadmin's guide to network management
https://opensource.com/article/18/7/sysadmin-guide-networking-commands

Xen Project Hypervisor: Virtualization and Power Management are Coalescing into an Energy-Aware Hypervisor
https://www.linux.com/blog/2018/7/xen-project-hypervisor-virtualization-and-power-management-are-coalescing

Users, Groups, and Other Linux Beasts
https://www.linux.com/learn/intro-to-linux/2018/7/users-groups-and-other-linux-beasts

Docker Guide: Dockerizing Python Django Application
https://www.howtoforge.com/tutorial/docker-guide-dockerizing-python-django-application/

How to easily purge unwanted repositories in Linux
https://www.techrepublic.com/article/how-to-easily-purge-unwanted-repositories-in-linux/

Early uses of blockchain will barely be visible, says Hyperledger’s Brian Behlendorf
https://techcrunch.com/2018/07/06/early-uses-of-blockchain-will-barely-be-visible/

Anatomy of a Linux DNS Lookup – Part I
https://zwischenzugs.com/2018/06/08/anatomy-of-a-linux-dns-lookup-part-i/

Anatomy of a Linux DNS Lookup – Part II
https://zwischenzugs.com/2018/06/18/anatomy-of-a-linux-dns-lookup-part-ii/

Anatomy of a Linux DNS Lookup – Part III
https://zwischenzugs.com/2018/07/06/anatomy-of-a-linux-dns-lookup-part-iii/

**Comment by BriFuture** [comment]
Pick.
Category: Javascript
Article: The Extensive Guide to Creating Streams in RxJS
https://blog.angularindepth.com/the-extensive-guide-to-creating-streams-in-rxjs-aaa02baaff9a

**Comment by MjSeven** [comment]
Python 有关的两篇：
Python Sets: What, Why and How
https://www.pythoncheatsheet.org/blog/python-sets-what-why-how
Understanding Python Dataclasses — Part 1
https://medium.com/mindorks/understanding-python-dataclasses-part-1-c3ccd4355c34
我申领一下喽

**Comment by oska874** [comment]
@BriFuture  @MjSeven  已经选题，给你们申领了，直接翻译吧

**Comment by MjSeven** [comment]
Linux
Docker Guide: Dockerizing Python Django Application
https://www.howtoforge.com/tutorial/docker-guide-dockerizing-python-django-application/
麻烦你了， @oska874

**Comment by oska874** [comment]
@MjSeven 已经选题&申领了，你可以开饭了

**Comment by MjSeven** [comment]
Got it!

**Comment by BriFuture** [comment]
Category：Node
Article：Testing Node.js in 2018
https://hackernoon.com/testing-node-js-in-2018-10a04dd77391
辛苦啦

**Comment by oska874** [comment]
@BriFuture 已选，开饭。

**Comment by BriFuture** [comment]
ok

**Comment by oska874** [comment]
@name1e5s  已选，开饭。

**Comment by oska874** [comment]
# *blockchain*

What is Ethereum?
https://www.linux.com/blog/holberton/2018/7/what-ethereum

**Comment by oska874** [comment]
# *ethernet*

DARPA Drops $35 Million on “Posh Open Source Hardware” Project
https://www.linux.com/blog/2018/7/darpa-drops-35-million-posh-open-source-hardware-project

**Comment by oska874** [comment]
# *docker*

10+ top open-source tools for Docker security
https://techbeacon.com/10-top-open-source-tools-docker-security

**Comment by oska874** [comment]
@bestony  已申领，请开饭

**Comment by oska874** [comment]
Weekend Reading: Raspberry Pi Projects



https://www.linuxjournal.com/content/weekend-reading-raspberry-pi-projects

**Comment by FSSlc** [comment]
@oska874 我想翻译下面这篇文章
4 Essential and Practical Usage of Cut Command in Linux
https://linuxhandbook.com/cut-command/

**Comment by oska874** [comment]
@FSSlc 已选，开饭

**Comment by oska874** [comment]
@martin2011qi 已选题申领，开饭

**Comment by oska874** [comment]
@pinewall 已选题，开饭
Anatomy of a Linux DNS Lookup – Part I

**Comment by bestony** [comment]
@oska874 申领 ：Becoming a senior developer: 9 experiences you'll encounter
https://www.hpe.com/us/en/insights/articles/becoming-a-senior-developer-9-experiences-youll-encounter-1807.html

**Comment by FSSlc** [comment]
我对下面三篇文章感兴趣，最近刚好有时间。我可以申领不？

netdev day 1: IPsec!
https://jvns.ca/blog/2018/07/11/netdev-day-1--ipsec/

netdev day 2: moving away from "as fast as possible" in networking code
https://jvns.ca/blog/2018/07/12/netdev-day-2--moving-away-from--as-fast-as-possible/

A sysadmin's guide to SELinux: 42 answers to the big questions
https://opensource.com/article/18/7/sysadmin-guide-selinux

**Comment by BriFuture** [comment]
Category：Node
Article: Twitter Sentiment Analysis using NodeJS
https://boostlog.io/@anshulc95/twitter-sentiment-analysis-using-nodejs-5ad1331247018500491f3b6a

**Comment by oska874** [comment]
@bestony Becoming a senior developer: 9 experiences you'll encounter 已选，开饭

**Comment by tiamit** [comment]
可以试试翻译，提交。

发自我的 iPad

**Comment by oska874** [comment]
@tiamit ？

**Comment by pinewall** [comment]
@oska874 Part I 翻译完了，继续申领 Part II
Anatomy of a Linux DNS Lookup – Part II
https://zwischenzugs.com/2018/06/18/anatomy-of-a-linux-dns-lookup-part-ii/

**Comment by oska874** [comment]
@pinewall Anatomy of a Linux DNS Lookup – Part II 已经给你选好了，直接update，开饭

**Comment by oska874** [comment]
@pinewall 已选，可以开饭。
Anatomy of a Linux DNS Lookup – Part III
https://zwischenzugs.com/2018/07/06/anatomy-of-a-linux-dns-lookup-part-iii/

**Comment by qhwdw** [comment]
@oska874 翻译下面这两篇，选题时直接加翻译标记“Translating by qhwdw"，我就不再另外 PR 了。 
https://itsfoss.com/linuxboot-uefi/
https://www.linux.com/blog/2018/10/greg-kroah-hartman-explains-how-kernel-community-securing-linux-0

**Comment by oska874** [comment]
@qhwdw ok，你先翻译，我随后补上md

**Comment by fengjixiong** [comment]
@oska874 我第一次翻译，是不是在你这边领稿？我对下面这个感兴趣
> tmate: Instantly Share Terminal Session With Other Linux Users
> https://linuxhandbook.com/tmate/
